#!/bin/bash

rvern="$(./vcs-revno)"

mkdir -p release

lrelease unetbootin.pro
./qmake-linux
make
strip --strip-all unetbootin
mv unetbootin release/unetbootin-linux-$rvern.bin
upx-ucl --best --lzma release/unetbootin-linux-$rvern.bin
