#!/bin/bash

rvern="$(./vcs-revno)"
make clean
rm Makefile*
rm release/*
lupdate unetbootin.pro
lrelease unetbootin.pro
./qmake-windows "DEFINES += AUTOSUPERGRUBDISK" "RESOURCES += unetbootin-autosupergrubdisk.qrc" "RESOURCES -= unetbootin-sevnz.qrc"
make
strip --strip-all release/unetbootin.exe
mv release/unetbootin.exe release/unetbootin-autosupergrubdisk-windows-$rvern.exe
upx-ucl --lzma release/unetbootin-autosupergrubdisk-windows-$rvern.exe
./qmake-linux "DEFINES += AUTOSUPERGRUBDISK" "RESOURCES += unetbootin-autosupergrubdisk.qrc"
make
strip --strip-all unetbootin
mv unetbootin release/unetbootin-autosupergrubdisk-linux-$rvern
upx-ucl --lzma release/unetbootin-autosupergrubdisk-linux-$rvern
qmake -spec linux-g++-32 "RESOURCES += unetbootin-linux.qrc"