#!/bin/bash

mingwb="$(ls /usr/ | grep mingw32 | head --lines 1)"
rvern="$(./vcs-revno)"
make clean
rm Makefile*
rm release/*
lupdate unetbootin.pro
lrelease unetbootin.pro
./qmake-windows "DEFINES += XPUD" "RESOURCES += unetbootin-xpud.qrc"
make
strip --strip-all release/unetbootin.exe
mv release/unetbootin.exe release/unetbootin-xpud-windows-$rvern.exe
upc-ucl --lzma release/unetbootin-xpud-windows-$rvern.exe
./qmake-linux "DEFINES += XPUD" "RESOURCES += unetbootin-xpud.qrc"
make
strip --strip-all unetbootin
mv unetbootin release/unetbootin-xpud-linux-$rvern
upc-ucl --lzma release/unetbootin-xpud-linux-$rvern
qmake -spec linux-g++-32 "RESOURCES += unetbootin-linux.qrc"

