#!/bin/bash

rvern="$(./vcs-revno)"
make clean
rm Makefile*
rm release/*
lupdate unetbootin.pro
lrelease unetbootin.pro
./qmake-windows "DEFINES += ELIVE" "RESOURCES += unetbootin-elive.qrc"
make
strip --strip-all release/unetbootin.exe
mv release/unetbootin.exe release/unetbootin-elive-windows-$rvern.exe
upx-ucl --lzma release/unetbootin-elive-windows-$rvern.exe
./qmake-linux "DEFINES += ELIVE" "RESOURCES += unetbootin-elive.qrc"
make
strip --strip-all unetbootin
mv unetbootin release/unetbootin-elive-linux-$rvern
upx-ucl --lzma release/unetbootin-elive-linux-$rvern
qmake -spec linux-g++-32 "RESOURCES += unetbootin-linux.qrc"

