#!/bin/bash

rvern="$(./vcs-revno)"

mkdir -p release

lrelease unetbootin.pro
./qmake-linux64
make
strip --strip-all unetbootin
mv unetbootin release/unetbootin-linux64-$rvern.bin
upc-ucl --best --lzma release/unetbootin-linux64-$rvern.bin