#!/bin/bash

rvern="$(./vcs-revno)"
make clean
rm Makefile*
rm release/*
lupdate unetbootin.pro
lrelease unetbootin.pro
./qmake-windows "DEFINES += KIWILINUX" "RESOURCES += unetbootin-kiwilinux.qrc"
make
strip --strip-all release/unetbootin.exe
mv release/unetbootin.exe release/unetbootin-kiwilinux-windows-$rvern.exe
upc-ucl --lzma release/unetbootin-kiwilinux-windows-$rvern.exe
./qmake-linux "DEFINES += KIWILINUX" "RESOURCES += unetbootin-kiwilinux.qrc"
make
strip --strip-all unetbootin
mv unetbootin release/unetbootin-kiwilinux-linux-$rvern
upx-ucl --lzma release/unetbootin-kiwilinux-linux-$rvern
qmake -spec linux-g++-32 "RESOURCES += unetbootin-linux.qrc"