#!/bin/bash

rvern="$(./vcs-revno)"
make clean
rm Makefile*
rm release/*
lupdate unetbootin.pro
lrelease unetbootin.pro
./qmake-windows "DEFINES += EEEPCLOS" "RESOURCES += unetbootin-eeepclos.qrc"
make
strip --strip-all release/unetbootin.exe
mv release/unetbootin.exe release/unetbootin-eeepclos-windows-$rvern.exe
upc-ucl --lzma release/unetbootin-eeepclos-windows-$rvern.exe
./qmake-linux "DEFINES += EEEPCLOS" "RESOURCES += unetbootin-eeepclos.qrc"
make
strip --strip-all unetbootin
mv unetbootin release/unetbootin-eeepclos-linux-$rvern
upc-ucl --lzma release/unetbootin-eeepclos-linux-$rvern
qmake -spec linux-g++-32 "RESOURCES += unetbootin-linux.qrc"

